weather:
  apikey: replaceme
  latitude: 0.0
  longitude: 0.0
  interval: 300

redis:
  server: localhost
  port: 6379

display:
  fbdev: /dev/fb1

sensor:
  gpio: 4
  type: DHT11
  pollinterval: 1
  updateinterval: 10
  averages: 5